### ISSUE TITLE
Java Oracle 1.8 installation

### ISSUE THREAD

**Issue by iGitScor** [shyiko/jabba#136]
Hi,

In your example, you talk about the version 8 of Oracle JDK
Unfortunately, it does not seem to work.

Do you know why ? And if it could be downloadable with jabba 
Which other JDK (Java 8) do you recommend between IBM, Zulu and Adopt ?

If the version 8 of Oracle is no more retrievable, maybe you could remove it from your documentation.

Thank you

**Comment by shyiko** [comment]
Hi Sebastien.

Yeah, only the latest stable + EAP versions of Oracle JDK / Oracle Server JRE can be installed (due to the Oracle distribution policy) (right now this means 1.9.x + 1.10.x). I can see how `jabba install 1.8` (in https://github.com/shyiko/jabba#usage) can be confusing. I'll update that.

As for alternatives. Zulu is the safest bet. I've been using it since 1.6 (on a pretty large scale deployments) and haven't experienced any problems with it. Adopt might be a good option once it matures.

**Comment by iGitScor** [comment]
Hi,

Thank you for the answer and for this amazing tool 😄
