### ISSUE TITLE
AdoptJDK 8u222 and 11.0.4 releases are not listed

### ISSUE THREAD

**Issue by normanmaurer** [shyiko/jabba#491]
AdoptJDK added new releases which are not discoverable via Jabba atm :/

**Comment by shyiko** [comment]
ha, looks like Travis CI is experiencing some kind of problems because https://travis-ci.org/shyiko/jabba-autodiscovery/builds (configured to "Run Daily") got triggered only twice in the last 4 days (last time 2 days ago - hence the delay in seeing 8u222 & 11.0.4). 
I'll set up an additional CI if this does not get resolved. Meanwhile - https://github.com/shyiko/jabba/pull/492 merged.
