### ISSUE TITLE
Windows: ‘jabba link system@1.8.201 C:\Program Files\Java\jdk1.8.0_201’ get error

### ISSUE THREAD

**Issue by magnetic1** [shyiko/jabba#582]
```
    PS C:\windows\system32> jabba link system@1.8.201 "C:\Program Files\Java\jdk1.8.0_201"
C:\Program\bin\java.exe wasn't found. If you believe this is an error - please create a ticket at https://github.com/shyiko/jabba/issues (specify OS and command that was used)
```

Possibly the spaces contained in the path are not handled correctly

**Comment by awkwardusername** [comment]
upping for relevance.
OS: Windows 10

```
PS C:\Users\Amatsukaze> jabba link system@1.11.0-6 "C:\Program Files\Java\jdk-11.0.6"
C:\Program\bin\java.exe wasn't found. If you believe this is an error - please create a ticket at https://github.com/shyiko/jabba/issues (specify OS and command that was used)
```

**Comment by michaelcusick** [comment]
I'll take a look at the .ps1 script today.

**Comment by Lipen** [comment]
I don't know Go, but I've delved into the code (beginning at [jabba.go:220](https://github.com/shyiko/jabba/blob/6c1726b87139ac0a910707f9b8e32d25ea58a8b8/jabba.go#L220-L238), where `cobra.Command` for `link` subcommand is being created) and it seems like everything is "okay" on its way to the place where the exception is thrown.

The problem is not in code itself, but in a way you pass the argument with spaces in Powershell: surprisingly, enquoting it (just like we always do in Unix) is not enough. You also have to "escape" each space using single-backtick before it:
```
PS C:\windows\system32> jabba link system@1.8.201 "C:\Program` Files\Java\jdk1.8.0_201"
                                                             ^ note the backtick
```
Found relevant answer on SO: https://stackoverflow.com/a/55064949/3592218.

**Comment by magnetic1** [comment]
@Lipen Thanks
I found two usable commands in this case from the link you provided.
```
PS C:\WINDOWS\system32>jabba link system@1.8.201 '"C:\Program Files\Java\jdk1.8.0_201"'
```
```
PS C:\WINDOWS\system32>jabba link system@1.8.201 'C:\Program` Files\Java\jdk1.8.0_201'
```
